# Diabete Disease Predicition

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

# 1 Get Data

In [3]:
diabete_df = pd.read_csv('diabetesCSV.csv')
diabete_df.head(5)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

# 2 Proprocess Data

In [4]:
diabete_df.shape

(767, 9)

In [5]:
diabete_df['Outcome'].value_counts()

0    499
1    268
Name: Outcome, dtype: int64

In [6]:
diabete_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 767 entries, 0 to 766
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               767 non-null    int64
 1   Glucose                   767 non-null    int64
 2   BloodPressure             767 non-null    int64
 3   SkinThickness             767 non-null    int64
 4   Insulin                   767 non-null    int64
 5   BMI                       767 non-null    float64
 6   DiabetesPedigreeFunction  767 non-null    float64
 7   Age                       767 non-null    int64
 8   Outcome                   767 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [7]:
diabete_df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,767.000000,767.000000,767.000000,767.000000,767.000000,767.000000,767.000000,767.000000,767.000000
mean,3.843546,120.894394,69.101695,20.533246,79.757497,32.000130,0.472172,33.245111,0.349413
std,3.371518,31.993481,19.368155,15.962378,115.313326,7.886525,0.331443,11.767322,0.477096
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243500,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,29.000000,32.000000,0.374000,29.000000,0.000000
75%,6.000000,140.500000,80.000000,32.000000,127.500000,36.600000,0.626500,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [8]:
diabete_df.groupby('Outcome').mean()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
Outcome,,,,,,,,
0,3.294589,109.957916,68.176353,19.657315,68.705411,30.312425,0.430104,31.192385
1,4.865672,141.257463,70.824627,22.164179,100.335821,35.142537,0.550500,37.067164

# 3 Separate Dependent & Independ Feature into x and y

In [9]:
X = diabete_df.drop('Outcome',axis=1)
y = diabete_df['Outcome']

In [10]:
print(X)

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6
1              1       85             66             29        0  26.6
2              8      183             64              0        0  23.3
3              1       89             66             23       94  28.1
4              0      137             40             35      168  43.1
..           ...      ...            ...            ...      ...   ...
762            9       89             62              0        0  22.5
763           10      101             76             48      180  32.9
764            2      122             70             27        0  36.8
765            1      126             60              0        0  30.1
766            1       93             70             31        0  30.4

     DiabetesPedigreeFunction  Age
0                       0.627   50
1                       0.351   31
2                       0.672   32
3                       0.167   21
4                       2.288   33
..                        ...  ...
762                     0.142   33
763                     0.171   63
764                     0.340   27
765                     0.349   47
766                     0.315   23

[767 rows x 8 columns]

In [11]:
print(y)

0      1
1      0
2      1
3      0
4      1
      ..
762    0
763    0
764    0
765    1
766    0
Name: Outcome, Length: 767, dtype: int64

# 5 Standarization

In [12]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X)
Standard_data = scaler.fit_transform(X)
X = Standard_data

In [13]:
X

array([[ 0.64002646,  0.84777563,  0.14974046, ...,  0.20299354,
         0.46743719,  1.42477805],
       [-0.84395266, -1.12266045, -0.16024856, ..., -0.68517558,
        -0.36582777, -0.19091649],
       [ 1.2336181 ,  1.94246234, -0.26357823, ..., -1.10388388,
         0.60329561, -0.10587993],
       ...,
       [-0.54715684,  0.03457979,  0.04641078, ...,  0.60901371,
        -0.39903761, -0.53106271],
       [-0.84395266,  0.15968684, -0.47023757, ..., -0.24109102,
        -0.37186592,  1.16966839],
       [-0.84395266, -0.87244635,  0.04641078, ..., -0.20302663,
        -0.47451451, -0.87120893]])

# 4 Train test split

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=25, random_state=1)

# 6 Train Model

In [15]:
from sklearn.linear_model import LogisticRegression
lg = LogisticRegression()

In [16]:
model = svm.SVC(kernel='linear')

In [17]:
lg.fit(X_train,y_train)

LogisticRegression()

In [18]:
train_y_pred = lg.predict(X_train)
test_y_pred = lg.predict(X_test)

# Accuracy

In [19]:
print('Train set Accuracy :',accuracy_score(train_y_pred,y_train))
print('Test set Accuracy :',accuracy_score(test_y_pred,y_test))

Train set Accuracy : 0.7762803234501348
Test set Accuracy : 0.84

# Prediction System

In [22]:
input_data = (1,85,66,29,0,26.6,0.351,31)
input_data_nparray = np.asarray(input_data)
reshaped_input_data = input_data_nparray.reshape(1,-1)
prediction = lg.predict(reshaped_input_data)

if prediction == 1:
    print('this person has a diabetes')
else:
    print("this person has not diabetes")

this person has a diabetes

In [21]:
diabete_df.head(100)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
95,6,144,72,27,228,33.9,0.255,40,0
96,2,92,62,28,0,31.6,0.130,24,0
97,1,71,48,18,76,20.4,0.323,22,0
98,6,93,50,30,64,28.7,0.356,23,0
99,1,122,90,51,220,49.7,0.325,31,1