### Sonar Rocks
##### Navigation obstacles such as reefs, rocks, corals and shoals are generally good sonar targets and can be detected out to the full range or our sonars.

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [4]:
df = pd.read_csv('Ocean_Sonar_Data.csv',header=None)
df.head()

,0,1,2,3,4,5,6,7,8,9,...,51,52,53,54,55,56,57,58,59,60
0,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,...,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032,R
1,0.0453,0.0523,0.0843,0.0689,0.1183,0.2583,0.2156,0.3481,0.3337,0.2872,...,0.0084,0.0089,0.0048,0.0094,0.0191,0.0140,0.0049,0.0052,0.0044,R
2,0.0262,0.0582,0.1099,0.1083,0.0974,0.2280,0.2431,0.3771,0.5598,0.6194,...,0.0232,0.0166,0.0095,0.0180,0.0244,0.0316,0.0164,0.0095,0.0078,R
3,0.0100,0.0171,0.0623,0.0205,0.0205,0.0368,0.1098,0.1276,0.0598,0.1264,...,0.0121,0.0036,0.0150,0.0085,0.0073,0.0050,0.0044,0.0040,0.0117,R
4,0.0762,0.0666,0.0481,0.0394,0.0590,0.0649,0.1209,0.2467,0.3564,0.4459,...,0.0031,0.0054,0.0105,0.0110,0.0015,0.0072,0.0048,0.0107,0.0094,R

In [5]:
#Here, '60' Column is our output
df[60].value_counts()

M    110
R     97
Name: 60, dtype: int64

In [6]:
df.groupby(60).mean()

,0,1,2,3,4,5,6,7,8,9,...,50,51,52,53,54,55,56,57,58,59
60,,,,,,,,,,,,,,,,,,,,,
M,0.035032,0.045637,0.050735,0.064804,0.087352,0.111650,0.128194,0.150174,0.213665,0.251164,...,0.019490,0.016081,0.011707,0.012181,0.009980,0.008963,0.007865,0.009071,0.008742,0.006949
R,0.022498,0.030303,0.035951,0.041447,0.062028,0.096224,0.114180,0.117596,0.137392,0.159325,...,0.012311,0.010453,0.009640,0.009518,0.008567,0.007430,0.007814,0.006677,0.007078,0.006024

In [7]:
#to check statistics
df.describe()

,0,1,2,3,4,5,6,7,8,9,...,50,51,52,53,54,55,56,57,58,59
count,207.000000,207.000000,207.000000,207.000000,207.000000,207.000000,207.000000,207.000000,207.000000,207.000000,...,207.000000,207.000000,207.000000,207.000000,207.000000,207.000000,207.000000,207.000000,207.000000,207.000000
mean,0.029158,0.038452,0.043807,0.053859,0.075485,0.104421,0.121627,0.134908,0.177923,0.208128,...,0.016126,0.013443,0.010739,0.010933,0.009318,0.008244,0.007842,0.007949,0.007962,0.006515
std,0.023047,0.033039,0.038520,0.046638,0.055537,0.059210,0.061914,0.085344,0.118669,0.134728,...,0.012009,0.009651,0.007065,0.007318,0.007094,0.005741,0.005791,0.006486,0.006189,0.005042
min,0.001500,0.000600,0.001500,0.005800,0.006700,0.010200,0.003300,0.005500,0.007500,0.011300,...,0.000000,0.000800,0.000500,0.001000,0.000600,0.000400,0.000300,0.000300,0.000100,0.000600
25%,0.013300,0.016400,0.018900,0.024350,0.038450,0.066950,0.080600,0.080350,0.096750,0.111150,...,0.008550,0.007250,0.005150,0.005350,0.004250,0.004450,0.003700,0.003600,0.003800,0.003100
50%,0.022800,0.030800,0.034200,0.044000,0.063000,0.092100,0.105600,0.111900,0.152200,0.181000,...,0.014000,0.011500,0.009600,0.009300,0.007500,0.006900,0.006000,0.005800,0.006500,0.005300
75%,0.035800,0.048100,0.058200,0.065700,0.101050,0.133450,0.154100,0.169800,0.234050,0.269000,...,0.020850,0.016750,0.014900,0.014500,0.012100,0.010650,0.010450,0.010400,0.010350,0.008550
max,0.137100,0.233900,0.305900,0.426400,0.401000,0.382300,0.372900,0.459000,0.682800,0.710600,...,0.100400,0.070900,0.039000,0.035200,0.044700,0.039400,0.035500,0.044000,0.036400,0.043900

In [8]:
#X and Y axis
X= df.drop(columns=60, axis=1)
y = df[60]

In [9]:
#Train test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)

In [10]:
X_train.shape

(186, 60)

In [11]:
X_test.shape

(21, 60)

In [12]:
#Call model and train dataset
model = LogisticRegression()
model.fit(X_train,y_train)

LogisticRegression()

In [13]:
#prediction for train data
train_pred = model.predict(X_train)
print(accuracy_score(train_pred,y_train))

0.8225806451612904

In [15]:
#prediction for test data set
test_pred = model.predict(X_test)
print(accuracy_score(test_pred,y_test))

0.8571428571428571

# Prediction

In [20]:
input_data = (0.0126, 0.0149, 0.0641, 0.1732, 0.2565, 0.2559, 0.2947, 0.411, 0.4983, 0.592, 0.5832, 0.5419, 0.5472, 0.5314, 0.4981, 0.6985, 0.8292, 0.7839, 0.8215, 0.9363, 1, 0.9224, 0.7839, 0.547, 0.4562, 0.5922, 0.5448, 0.3971, 0.0882, 0.2385, 0.2005, 0.0587, 0.2544, 0.2009, 0.0329, 0.1547, 0.1212, 0.2446, 0.3171, 0.3195, 0.3051, 0.0836, 0.1266, 0.1381, 0.1136, 0.0516, 0.0073, 0.0278, 0.0372, 0.0121, 0.0153, 0.0092, 0.0035, 0.0098, 0.0121, 0.0006, 0.0181, 0.0094, 0.0116, 0.0063)
input_data_np = np.asarray(input_data)
reshaped_input_data = input_data_np.reshape(1,-1)
prediction = model.predict(reshaped_input_data)

if prediction[0] == 'R':
    print("This is Rock")
else:
    print("This is Mine")

This is Mine