In [10]:
import numpy as np
import pandas as pd

In [11]:
#load the dataset
df = pd.read_csv("BreastCancerCSV.csv")
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [12]:
#'diagnosis' column is our Output column

In [13]:
#count the unique values
df['diagnosis'].value_counts()

B    356
M    212
Name: diagnosis, dtype: int64

In [14]:
#Above we have 2 output,=> classification based problem statement

In [15]:
#To check the shape of dataset
df.shape

(568, 32)

In [16]:
#To check the missing/null value
df.isnull().sum()

id                         0
diagnosis                  0
radius_mean                0
texture_mean               0
perimeter_mean             0
area_mean                  0
smoothness_mean            0
compactness_mean           0
concavity_mean             0
concave points_mean        0
symmetry_mean              0
fractal_dimension_mean     0
radius_se                  0
texture_se                 0
perimeter_se               0
area_se                    0
smoothness_se              0
compactness_se             0
concavity_se               0
concave points_se          0
symmetry_se                0
fractal_dimension_se       0
radius_worst               0
texture_worst              0
perimeter_worst            0
area_worst                 0
smoothness_worst           0
compactness_worst          0
concavity_worst            0
concave points_worst       0
symmetry_worst             0
fractal_dimension_worst    0
dtype: int64

In [17]:
#To check the duplicated value
df.duplicated().sum()

0

In [18]:
#to check the datatype
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 568 entries, 0 to 567
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       568 non-null    int64
 1   diagnosis                568 non-null    object
 2   radius_mean              568 non-null    float64
 3   texture_mean             568 non-null    float64
 4   perimeter_mean           568 non-null    float64
 5   area_mean                568 non-null    float64
 6   smoothness_mean          568 non-null    float64
 7   compactness_mean         568 non-null    float64
 8   concavity_mean           568 non-null    float64
 9   concave points_mean      568 non-null    float64
 10  symmetry_mean            568 non-null    float64
 11  fractal_dimension_mean   568 non-null    float64
 12  radius_se                568 non-null    float64
 13  texture_se               568 non-null    float64
 14  perimeter_se             568 non-null    float64
 15  area_se                  568 non-null    float64
 16  smoothness_se            568 non-null    float64
 17  compactness_se           568 non-null    float64
 18  concavity_se             568 non-null    float64
 19  concave points_se        568 non-null    float64
 20  symmetry_se              568 non-null    float64
 21  fractal_dimension_se     568 non-null    float64
 22  radius_worst             568 non-null    float64
 23  texture_worst            568 non-null    float64
 24  perimeter_worst          568 non-null    float64
 25  area_worst               568 non-null    float64
 26  smoothness_worst         568 non-null    float64
 27  compactness_worst        568 non-null    float64
 28  concavity_worst          568 non-null    float64
 29  concave points_worst     568 non-null    float64
 30  symmetry_worst           568 non-null    float64
 31  fractal_dimension_worst  568 non-null    float64
dtypes: float64(30), int64(1), object(1)
memory usage: 142.1+ KB

In [19]:
#To check the basic statistic
df.describe()

,id,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
count,5.680000e+02,568.000000,568.000000,568.000000,568.000000,568.000000,568.000000,568.000000,568.000000,568.000000,...,568.000000,568.000000,568.000000,568.000000,568.000000,568.000000,568.000000,568.000000,568.000000,568.000000
mean,3.042367e+07,14.126477,19.283680,91.961250,654.885211,0.096381,0.104291,0.088774,0.048939,0.181225,...,16.270579,25.674419,107.263609,880.842077,0.132421,0.254154,0.272023,0.114613,0.290189,0.083953
std,1.251247e+08,3.527101,4.302467,24.319689,352.224310,0.014068,0.052846,0.079788,0.038834,0.027397,...,4.837388,6.151311,33.632112,569.825313,0.022818,0.157453,0.208771,0.065790,0.061863,0.018076
min,8.670000e+03,6.981000,9.710000,43.790000,143.500000,0.052630,0.019380,0.000000,0.000000,0.106000,...,7.930000,12.020000,50.410000,185.200000,0.071170,0.027290,0.000000,0.000000,0.156500,0.055040
25%,8.691895e+05,11.697500,16.170000,75.135000,420.175000,0.086400,0.064815,0.029540,0.020310,0.161975,...,13.010000,21.075000,84.102500,514.975000,0.116600,0.146900,0.114475,0.064730,0.250475,0.071412
50%,9.060010e+05,13.355000,18.835000,86.210000,548.750000,0.095895,0.092525,0.061400,0.033455,0.179250,...,14.965000,25.405000,97.655000,685.550000,0.131350,0.211850,0.226550,0.099840,0.282250,0.080025
75%,8.825022e+06,15.797500,21.785000,104.150000,784.150000,0.105325,0.130400,0.131000,0.074010,0.195700,...,18.795000,29.757500,125.525000,1085.000000,0.146025,0.339300,0.383500,0.161675,0.318025,0.092082
max,9.113205e+08,28.110000,39.280000,188.500000,2501.000000,0.163400,0.345400,0.426800,0.201200,0.304000,...,36.040000,49.540000,251.200000,4254.000000,0.222600,1.058000,1.252000,0.291000,0.663800,0.207500

In [20]:
#To check the corelation: 2 type posive and negative
corr = df.corr()
corr

,id,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
id,1.000000,0.074686,0.100157,0.073241,0.096900,-0.013320,0.000321,0.050157,0.044040,-0.022691,...,0.082343,0.064834,0.079973,0.107091,0.009812,-0.002803,0.023395,0.035149,-0.044701,-0.029958
radius_mean,0.074686,1.000000,0.323782,0.997857,0.987371,0.170878,0.506137,0.676752,0.822674,0.148268,...,0.969614,0.296970,0.965162,0.941212,0.120100,0.413435,0.526909,0.744243,0.164353,0.007116
texture_mean,0.100157,0.323782,1.000000,0.329470,0.321253,-0.022264,0.236139,0.302346,0.294062,0.073365,...,0.353002,0.912238,0.358293,0.344114,0.079479,0.277465,0.300617,0.295566,0.106612,0.119576
perimeter_mean,0.073241,0.997857,0.329470,1.000000,0.986534,0.207675,0.556923,0.716120,0.851164,0.183727,...,0.969580,0.302982,0.970430,0.941716,0.151199,0.455723,0.563852,0.771286,0.189635,0.051092
area_mean,0.096900,0.987371,0.321253,0.986534,1.000000,0.177144,0.498625,0.686000,0.823337,0.151535,...,0.962771,0.287503,0.959121,0.959273,0.123723,0.390461,0.512693,0.722020,0.143718,0.003740
smoothness_mean,-0.013320,0.170878,-0.022264,0.207675,0.177144,1.000000,0.660484,0.522571,0.553638,0.557044,...,0.213015,0.036474,0.238938,0.206478,0.805115,0.473403,0.435924,0.503268,0.393406,0.499323
compactness_mean,0.000321,0.506137,0.236139,0.556923,0.498625,0.660484,1.000000,0.883205,0.831701,0.604955,...,0.535623,0.247964,0.590403,0.510014,0.567788,0.865773,0.816202,0.815848,0.511838,0.687796
concavity_mean,0.050157,0.676752,0.302346,0.716120,0.686000,0.522571,0.883205,1.000000,0.921582,0.501841,...,0.688323,0.299824,0.729599,0.676126,0.449916,0.754970,0.884145,0.861369,0.410190,0.515033
concave points_mean,0.044040,0.822674,0.294062,0.851164,0.823337,0.553638,0.831701,0.921582,1.000000,0.462543,...,0.830316,0.292928,0.855970,0.809605,0.452783,0.667810,0.752830,0.910197,0.375585,0.368592
symmetry_mean,-0.022691,0.148268,0.073365,0.183727,0.151535,0.557044,0.604955,0.501841,0.462543,1.000000,...,0.185635,0.091390,0.219405,0.176875,0.424950,0.474899,0.435490,0.430801,0.699150,0.438593
fractal_dimension_mean,-0.052594,-0.311602,-0.076220,-0.261432,-0.283117,0.584889,0.565713,0.336862,0.166837,0.480225,...,-0.253760,-0.051188,-0.205171,-0.231961,0.505283,0.459009,0.346456,0.175311,0.334003,0.767281
radius_se,0.142838,0.679503,0.277024,0.692250,0.732841,0.300815,0.498408,0.632379,0.698023,0.302454,...,0.715160,0.195179,0.719905,0.751576,0.140691,0.287707,0.381309,0.531190,0.093479,0.049333
texture_se,-0.007609,-0.097277,0.386857,-0.086703,-0.066280,0.068162,0.046407,0.076285,0.021378,0.127795,...,-0.111754,0.409131,-0.102260,-0.083293,-0.074225,-0.092317,-0.068814,-0.119664,-0.128703,-0.045733
perimeter_se,0.137218,0.674315,0.282294,0.693319,0.726696,0.295834,0.549401,0.660567,0.710602,0.313661,...,0.697188,0.200546,0.721074,0.730676,0.129530,0.342222,0.419264,0.554914,0.109463,0.085323
area_se,0.177593,0.736116,0.260671,0.745289,0.800239,0.246079,0.456293,0.617700,0.690240,0.223295,...,0.757399,0.196754,0.761321,0.811397,0.124548,0.283671,0.385604,0.538217,0.073372,0.017369
smoothness_se,0.096472,-0.222558,0.007920,-0.202556,-0.166894,0.331470,0.136331,0.098933,0.027187,0.185597,...,-0.231142,-0.074378,-0.217537,-0.182771,0.313023,-0.054951,-0.057612,-0.102188,-0.109238,0.101207
compactness_se,0.034489,0.205981,0.190685,0.250678,0.212826,0.321226,0.738685,0.670740,0.491668,0.425496,...,0.205195,0.142649,0.260914,0.200156,0.230703,0.678870,0.639102,0.483921,0.280623,0.592155
concavity_se,0.055770,0.194163,0.141968,0.227982,0.207879,0.250462,0.570224,0.691708,0.440281,0.346114,...,0.187440,0.099845,0.227013,0.189085,0.171510,0.484674,0.662527,0.441088,0.200258,0.440265
concave points_se,0.079092,0.376173,0.163048,0.407179,0.372470,0.382075,0.642038,0.683351,0.616305,0.395648,...,0.358485,0.086467,0.395216,0.342751,0.217357,0.452656,0.549373,0.602782,0.144580,0.311062
symmetry_se,-0.017520,-0.104229,0.009835,-0.081488,-0.072507,0.200206,0.230570,0.178211,0.095115,0.448752,...,-0.128297,-0.077265,-0.103812,-0.110603,-0.013843,0.060632,0.037534,-0.030476,0.388937,0.077908
fractal_dimension_se,0.025824,-0.042697,0.054169,-0.005598,-0.019890,0.284128,0.507253,0.449262,0.257737,0.332833,...,-0.037424,-0.003301,-0.000984,-0.022633,0.171364,0.390069,0.379877,0.215240,0.111629,0.591468
radius_worst,0.082343,0.969614,0.353002,0.969580,0.962771,0.213015,0.535623,0.688323,0.830316,0.185635,...,1.000000,0.360025,0.993721,0.984021,0.216529,0.476013,0.574221,0.787427,0.243468,0.093436
texture_worst,0.064834,0.296970,0.912238,0.302982,0.287503,0.036474,0.247964,0.299824,0.292928,0.091390,...,0.360025,1.000000,0.365139,0.346001,0.226378,0.360722,0.368247,0.359806,0.233739,0.219243
perimeter_worst,0.079973,0.965162,0.358293,0.970430,0.959121,0.238938,0.590403,0.729599,0.855970,0.219405,...,0.993721,0.365139,1.000000,0.977619,0.237037,0.529511,0.618488,0.816322,0.269676,0.138947
area_worst,0.107091,0.941212,0.344114,0.941716,0.959273,0.206478,0.510014,0.676126,0.809605,0.176875,...,0.984021,0.346001,0.977619,1.000000,0.208877,0.438566,0.543665,0.747437,0.208883,0.079556
smoothness_worst,0.009812,0.120100,0.079479,0.151199,0.123723,0.805115,0.567788,0.449916,0.452783,0.424950,...,0.216529,0.226378,0.237037,0.208877,1.000000,0.570040,0.520433,0.548372,0.492657,0.618080
compactness_worst,-0.002803,0.413435,0.277465,0.455723,0.390461,0.473403,0.865773,0.754970,0.667810,0.474899,...,0.476013,0.360722,0.529511,0.438566,0.570040,1.000000,0.892229,0.801240,0.615845,0.810755
concavity_worst,0.023395,0.526909,0.300617,0.563852,0.512693,0.435924,0.816202,0.884145,0.752830,0.435490,...,0.574221,0.368247,0.618488,0.543665,0.520433,0.892229,1.000000,0.855640,0.533949,0.686834
concave points_worst,0.035149,0.744243,0.295566,0.771286,0.722020,0.503268,0.815848,0.861369,0.910197,0.430801,...,0.787427,0.359806,0.816322,0.747437,0.548372,0.801240,0.855640,1.000000,0.502895,0.511113
symmetry_worst,-0.044701,0.164353,0.106612,0.189635,0.143718,0.393406,0.511838,0.410190,0.375585,0.699150,...,0.243468,0.233739,0.269676,0.208883,0.492657,0.615845,0.533949,0.502895,1.000000,0.537986
fractal_dimension_worst,-0.029958,0.007116,0.119576,0.051092,0.003740,0.499323,0.687796,0.515033,0.368592,0.438593,...,0.093436,0.219243,0.138947,0.079556,0.618080,0.810755,0.686834,0.511113,0.537986,1.000000

# Encoding the Target Variable

In [21]:
#wkt, the unique value
df['diagnosis'].value_counts()

B    356
M    212
Name: diagnosis, dtype: int64

In [22]:
#LabelEncoding: if our output variable is categorical value
# from sklearn.preprocessing import LabelEncoder
# le = LabelEncoder()
#Note but I do using normal/general way

In [23]:
df['diagnosis'] = df['diagnosis'].map({"M":1,"B":0})

In [24]:
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,842302,1,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,842517,1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,84300903,1,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,84348301,1,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,84358402,1,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [25]:
df['diagnosis'].value_counts()

0    356
1    212
Name: diagnosis, dtype: int64

# Train test split set

In [27]:
X = df.drop('diagnosis', axis=1)
y = df['diagnosis']

In [28]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.2,random_state=42)
X_train.shape

(454, 31)

In [29]:
X_test.shape

(114, 31)

# Feature Scaler

In [30]:
#Our data is unscaled which does not give correct ouput

In [33]:
X_train.std()

id                         1.123813e+08
radius_mean                3.531082e+00
texture_mean               4.225884e+00
perimeter_mean             2.427240e+01
area_mean                  3.555177e+02
smoothness_mean            1.401020e-02
compactness_mean           5.106817e-02
concavity_mean             7.866716e-02
concave points_mean        3.822485e-02
symmetry_mean              2.727099e-02
fractal_dimension_mean     7.099381e-03
radius_se                  2.846270e-01
texture_se                 5.220307e-01
perimeter_se               2.088176e+00
area_se                    4.733180e+01
smoothness_se              3.068093e-03
compactness_se             1.814320e-02
concavity_se               2.949647e-02
concave points_se          6.272010e-03
symmetry_se                8.137452e-03
fractal_dimension_se       2.752957e-03
radius_worst               4.830071e+00
texture_worst              6.058413e+00
perimeter_worst            3.357974e+01
area_worst                 5.706939e+02
smoothness_worst           2.271352e-02
compactness_worst          1.505537e-01
concavity_worst            1.980987e-01
concave points_worst       6.513584e-02
symmetry_worst             6.235391e-02
fractal_dimension_worst    1.690044e-02
dtype: float64

In [32]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
sc.fit(X_train)

StandardScaler()

In [34]:
X_train = sc.transform(X_train)
X_test = sc.transform(X_test)

In [35]:
X_train

array([[ 0.54730934, -0.97037885,  1.461081  , ..., -0.79808167,
         0.82335125, -0.10227618],
       [-0.23308597, -0.48557379,  0.65089009, ...,  0.11086867,
         0.12173998,  0.55760535],
       [-0.23276727, -0.50258449, -0.00768614, ..., -1.12898631,
        -0.54936646, -0.65908825],
       ...,
       [-0.16138363,  0.06160385, -0.52886157, ..., -1.22888785,
        -0.70349617, -1.30297625],
       [-0.23266825, -0.02628478,  0.13445262, ...,  1.06684958,
         0.45408216,  1.32114871],
       [-0.23307379, -0.5366059 ,  0.34766075, ..., -0.59904705,
        -0.32459397, -0.85397248]])

# Train Model

In [36]:
from sklearn.linear_model import LogisticRegression
lg = LogisticRegression()

In [37]:
lg.fit(X_train,y_train)
y_pred = lg.predict(X_test)
y_pred

array([1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0], dtype=int64)

In [38]:
#To evaluate model
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9649122807017544

# Prediction System

In [41]:
input_text = (0.54730934, -0.97037885,  1.461081  , -0.96996455, -0.85415251,
        0.0246505 , -0.58423012, -0.79495231, -0.83335045,  0.32542846,
        0.08858644, -0.54228349,  0.55833183, -0.65485014, -0.49585814,
        0.05015239, -0.80463757, -0.69886841, -0.89094973,  0.13095894,
       -0.41671743, -0.81688677,  1.62074922, -0.85592554, -0.73103109,
        0.79110823, -0.71159565, -0.76264163, -0.79808167,  0.82335125,
       -0.10227618)
np_df = np.asarray(input_text)
prediction= lg.predict(np_df.reshape(1,-1))
if prediction[0] == 1:
    print("Cancrous")
else:
    print("Not Cancer")

Not Cancer