# Parkinson Disease Prediction Model

In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("parkinsons.data")
df.head()

,name,MDVP:Fo(Hz),MDVP:Fhi(Hz),MDVP:Flo(Hz),MDVP:Jitter(%),MDVP:Jitter(Abs),MDVP:RAP,MDVP:PPQ,Jitter:DDP,MDVP:Shimmer,...,Shimmer:DDA,NHR,HNR,status,RPDE,DFA,spread1,spread2,D2,PPE
0,phon_R01_S01_1,119.992,157.302,74.997,0.00784,0.00007,0.00370,0.00554,0.01109,0.04374,...,0.06545,0.02211,21.033,1,0.414783,0.815285,-4.813031,0.266482,2.301442,0.284654
1,phon_R01_S01_2,122.400,148.650,113.819,0.00968,0.00008,0.00465,0.00696,0.01394,0.06134,...,0.09403,0.01929,19.085,1,0.458359,0.819521,-4.075192,0.335590,2.486855,0.368674
2,phon_R01_S01_3,116.682,131.111,111.555,0.01050,0.00009,0.00544,0.00781,0.01633,0.05233,...,0.08270,0.01309,20.651,1,0.429895,0.825288,-4.443179,0.311173,2.342259,0.332634
3,phon_R01_S01_4,116.676,137.871,111.366,0.00997,0.00009,0.00502,0.00698,0.01505,0.05492,...,0.08771,0.01353,20.644,1,0.434969,0.819235,-4.117501,0.334147,2.405554,0.368975
4,phon_R01_S01_5,116.014,141.781,110.655,0.01284,0.00011,0.00655,0.00908,0.01966,0.06425,...,0.10470,0.01767,19.649,1,0.417356,0.823484,-3.747787,0.234513,2.332180,0.410335

In [5]:
#Here we have complex dataset, but we can proceed with this dataset
#Using Sound waves we have collected the dataset

In [7]:
"""
name: The name of the patient as a string.
MDVP:Fo(Hz): The average fundamental frequency measured in Hz.
MDVP:Fhi(Hz): The highest fundamental frequency measured in Hz.
MDVP:Flo(Hz): The lowest fundamental frequency measured in Hz.
MDVP:Jitter(%): The percentage of the absolute jitter, which is defined as the variation in the fundamental frequency, relative to the fundamental frequency.
MDVP:Jitter(Abs): The absolute jitter, measured in Hz.
MDVP:RAP: The relative amplitude perturbation, which is defined as the average absolute difference between consecutive signal periods divided by the average signal period.
MDVP:PPQ: The pitch period perturbation quotient, which is similar to the RAP but only takes into account the pitch periods.
Jitter:DDP: The average absolute difference between consecutive signal periods divided by three times the average signal period.
MDVP:Shimmer: The amplitude variation of the signal in dB.
MDVP:Shimmer(dB): The amplitude variation of the signal in dB.
Shimmer:APQ3: The amplitude perturbation quotient measured in dB, which only takes into account the first three harmonics.
Shimmer:APQ5: The amplitude perturbation quotient measured in dB, which only takes into account the first five harmonics.
MDVP:APQ: The amplitude perturbation quotient measured in dB, which takes into account all harmonics.
Shimmer:DDA: The average absolute difference between consecutive signal periods divided by the signal length, measured in dB.
NHR: The ratio of the noise to the harmonic components in the voice.
HNR: The ratio of the energy in the harmonic components to the energy in the noise.
status: A binary variable that indicates whether the patient has Parkinson's disease (1) or not (0).
RPDE: The relative average perturbation entropy, which is a measure of the unpredictability of the signal.
DFA: The detrended fluctuation analysis, which measures the scaling behavior of the signal.
spread1: A nonlinear measure of the speech signal.
spread2: Another nonlinear measure of the speech signal.
D2: The correlation dimension, which measures the fractal dimension of the signal.
PPE: The pitch period entropy, which measures the disorder and complexity of the signal.
"""

"\nname: The name of the patient as a string.\nMDVP:Fo(Hz): The average fundamental frequency measured in Hz.\nMDVP:Fhi(Hz): The highest fundamental frequency measured in Hz.\nMDVP:Flo(Hz): The lowest fundamental frequency measured in Hz.\nMDVP:Jitter(%): The percentage of the absolute jitter, which is defined as the variation in the fundamental frequency, relative to the fundamental frequency.\nMDVP:Jitter(Abs): The absolute jitter, measured in Hz.\nMDVP:RAP: The relative amplitude perturbation, which is defined as the average absolute difference between consecutive signal periods divided by the average signal period.\nMDVP:PPQ: The pitch period perturbation quotient, which is similar to the RAP but only takes into account the pitch periods.\nJitter:DDP: The average absolute difference between consecutive signal periods divided by three times the average signal period.\nMDVP:Shimmer: The amplitude variation of the signal in dB.\nMDVP:Shimmer(dB): The amplitude variation of the signal in dB.\nShimmer:APQ3: The amplitude perturbation quotient measured in dB, which only takes into account the first three harmonics.\nShimmer:APQ5: The amplitude perturbation quotient measured in dB, which only takes into account the first five harmonics.\nMDVP:APQ: The amplitude perturbation quotient measured in dB, which takes into account all harmonics.\nShimmer:DDA: The average absolute difference between consecutive signal periods divided by the signal length, measured in dB.\nNHR: The ratio of the noise to the harmonic components in the voice.\nHNR: The ratio of the energy in the harmonic components to the energy in the noise.\nstatus: A binary variable that indicates whether the patient has Parkinson's disease (1) or not (0).\nRPDE: The relative average perturbation entropy, which is a measure of the unpredictability of the signal.\nDFA: The detrended fluctuation analysis, which measures the scaling behavior of the signal.\nspread1: A nonlinear measure of the speech signal.\nspread2: Another nonlinear measure of the speech signal.\nD2: The correlation dimension, which measures the fractal dimension of the signal.\nPPE: The pitch period entropy, which measures the disorder and complexity of the signal.\n"

In [8]:
#To check the size of dataset
df.shape

(194, 24)

In [9]:
#To check the null values
df.isnull().sum()

name                0
MDVP:Fo(Hz)         0
MDVP:Fhi(Hz)        0
MDVP:Flo(Hz)        0
MDVP:Jitter(%)      0
MDVP:Jitter(Abs)    0
MDVP:RAP            0
MDVP:PPQ            0
Jitter:DDP          0
MDVP:Shimmer        0
MDVP:Shimmer(dB)    0
Shimmer:APQ3        0
Shimmer:APQ5        0
MDVP:APQ            0
Shimmer:DDA         0
NHR                 0
HNR                 0
status              0
RPDE                0
DFA                 0
spread1             0
spread2             0
D2                  0
PPE                 0
dtype: int64

In [10]:
#TO Check the duplicated values
df.duplicated().sum()

0

In [11]:
#To check the info(datatype)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 194 entries, 0 to 193
Data columns (total 24 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   name              194 non-null    object
 1   MDVP:Fo(Hz)       194 non-null    float64
 2   MDVP:Fhi(Hz)      194 non-null    float64
 3   MDVP:Flo(Hz)      194 non-null    float64
 4   MDVP:Jitter(%)    194 non-null    float64
 5   MDVP:Jitter(Abs)  194 non-null    float64
 6   MDVP:RAP          194 non-null    float64
 7   MDVP:PPQ          194 non-null    float64
 8   Jitter:DDP        194 non-null    float64
 9   MDVP:Shimmer      194 non-null    float64
 10  MDVP:Shimmer(dB)  194 non-null    float64
 11  Shimmer:APQ3      194 non-null    float64
 12  Shimmer:APQ5      194 non-null    float64
 13  MDVP:APQ          194 non-null    float64
 14  Shimmer:DDA       194 non-null    float64
 15  NHR               194 non-null    float64
 16  HNR               194 non-null    float64
 17  status            194 non-null    int64
 18  RPDE              194 non-null    float64
 19  DFA               194 non-null    float64
 20  spread1           194 non-null    float64
 21  spread2           194 non-null    float64
 22  D2                194 non-null    float64
 23  PPE               194 non-null    float64
dtypes: float64(22), int64(1), object(1)
memory usage: 36.5+ KB

In [12]:
#To check the statistics
df.describe()

,MDVP:Fo(Hz),MDVP:Fhi(Hz),MDVP:Flo(Hz),MDVP:Jitter(%),MDVP:Jitter(Abs),MDVP:RAP,MDVP:PPQ,Jitter:DDP,MDVP:Shimmer,MDVP:Shimmer(dB),...,Shimmer:DDA,NHR,HNR,status,RPDE,DFA,spread1,spread2,D2,PPE
count,194.000000,194.000000,194.000000,194.000000,194.000000,194.000000,194.000000,194.000000,194.000000,194.000000,...,194.000000,194.000000,194.000000,194.000000,194.000000,194.000000,194.000000,194.000000,194.000000,194.000000
mean,153.999077,196.074732,116.538139,0.006214,0.000044,0.003304,0.003444,0.009914,0.029744,0.282464,...,0.047039,0.024603,21.900747,0.757732,0.498779,0.718481,-5.678932,0.226609,2.383080,0.206981
std,41.372505,90.587264,43.531508,0.004860,0.000035,0.002975,0.002766,0.008926,0.018899,0.195359,...,0.030531,0.040378,4.432392,0.429564,0.104155,0.055220,1.090347,0.083610,0.383388,0.090153
min,88.333000,102.145000,65.476000,0.001680,0.000007,0.000680,0.000920,0.002040,0.009540,0.085000,...,0.013640,0.000650,8.441000,0.000000,0.256570,0.574282,-7.964984,0.006274,1.423287,0.044539
25%,117.423000,134.759250,84.768750,0.003460,0.000020,0.001660,0.001860,0.004982,0.016473,0.148250,...,0.024668,0.005913,19.217250,1.000000,0.420845,0.675181,-6.445950,0.173935,2.097181,0.138601
50%,148.626000,174.402000,104.376000,0.004940,0.000030,0.002485,0.002680,0.007455,0.023025,0.219000,...,0.038435,0.011635,22.152000,1.000000,0.496717,0.722305,-5.716036,0.219660,2.363666,0.195294
75%,181.758000,223.311500,140.532750,0.007315,0.000060,0.003853,0.003958,0.011558,0.037992,0.350000,...,0.060883,0.025180,25.097250,1.000000,0.588759,0.762195,-5.034240,0.279512,2.637367,0.253268
max,260.105000,592.030000,239.170000,0.033160,0.000260,0.021440,0.019580,0.064330,0.119080,1.302000,...,0.169420,0.314820,33.047000,1.000000,0.685151,0.825288,-2.434031,0.450493,3.671155,0.527367

# About Output Variable:
1 147 No Disease



0 48 have Disease

In [14]:
# df['status'] is our ouput columns
df['status'].value_counts()

1    147
0     47
Name: status, dtype: int64

In [15]:
#lets check teh mean for status column
df.groupby('status').mean()

,MDVP:Fo(Hz),MDVP:Fhi(Hz),MDVP:Flo(Hz),MDVP:Jitter(%),MDVP:Jitter(Abs),MDVP:RAP,MDVP:PPQ,Jitter:DDP,MDVP:Shimmer,MDVP:Shimmer(dB),...,MDVP:APQ,Shimmer:DDA,NHR,HNR,RPDE,DFA,spread1,spread2,D2,PPE
status,,,,,,,,,,,,,,,,,,,,,
0,181.579766,219.949000,146.703106,0.003791,0.000023,0.001887,0.002017,0.005663,0.017501,0.161298,...,0.01325,0.028311,0.010190,24.799149,0.442367,0.696817,-6.759576,0.159289,2.154829,0.123011
1,145.180762,188.441463,106.893558,0.006989,0.000051,0.003757,0.003900,0.011273,0.033658,0.321204,...,0.02760,0.053027,0.029211,20.974048,0.516816,0.725408,-5.333420,0.248133,2.456058,0.233828

In [16]:
#I don't need Name colun
#split into x and y axis
X = df.drop(['status','name'], axis=1)
y = df['status']

In [17]:
X.shape

(194, 22)

In [18]:
y.shape

(194,)

In [20]:
#Train and test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.2,random_state=2)

In [21]:
X.shape

(194, 22)

In [22]:
y.shape

(194,)

In [23]:
X

,MDVP:Fo(Hz),MDVP:Fhi(Hz),MDVP:Flo(Hz),MDVP:Jitter(%),MDVP:Jitter(Abs),MDVP:RAP,MDVP:PPQ,Jitter:DDP,MDVP:Shimmer,MDVP:Shimmer(dB),...,MDVP:APQ,Shimmer:DDA,NHR,HNR,RPDE,DFA,spread1,spread2,D2,PPE
0,119.992,157.302,74.997,0.00784,0.00007,0.00370,0.00554,0.01109,0.04374,0.426,...,0.02971,0.06545,0.02211,21.033,0.414783,0.815285,-4.813031,0.266482,2.301442,0.284654
1,122.400,148.650,113.819,0.00968,0.00008,0.00465,0.00696,0.01394,0.06134,0.626,...,0.04368,0.09403,0.01929,19.085,0.458359,0.819521,-4.075192,0.335590,2.486855,0.368674
2,116.682,131.111,111.555,0.01050,0.00009,0.00544,0.00781,0.01633,0.05233,0.482,...,0.03590,0.08270,0.01309,20.651,0.429895,0.825288,-4.443179,0.311173,2.342259,0.332634
3,116.676,137.871,111.366,0.00997,0.00009,0.00502,0.00698,0.01505,0.05492,0.517,...,0.03772,0.08771,0.01353,20.644,0.434969,0.819235,-4.117501,0.334147,2.405554,0.368975
4,116.014,141.781,110.655,0.01284,0.00011,0.00655,0.00908,0.01966,0.06425,0.584,...,0.04465,0.10470,0.01767,19.649,0.417356,0.823484,-3.747787,0.234513,2.332180,0.410335
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,201.774,262.707,78.228,0.00694,0.00003,0.00412,0.00396,0.01235,0.02574,0.255,...,0.01758,0.04363,0.04441,19.368,0.508479,0.683761,-6.934474,0.159890,2.316346,0.112838
190,174.188,230.978,94.261,0.00459,0.00003,0.00263,0.00259,0.00790,0.04087,0.405,...,0.02745,0.07008,0.02764,19.517,0.448439,0.657899,-6.538586,0.121952,2.657476,0.133050
191,209.516,253.017,89.488,0.00564,0.00003,0.00331,0.00292,0.00994,0.02751,0.263,...,0.01879,0.04812,0.01810,19.147,0.431674,0.683244,-6.195325,0.129303,2.784312,0.168895
192,174.688,240.005,74.287,0.01360,0.00008,0.00624,0.00564,0.01873,0.02308,0.256,...,0.01667,0.03804,0.10715,17.883,0.407567,0.655683,-6.787197,0.158453,2.679772,0.131728
193,214.289,260.277,77.973,0.00567,0.00003,0.00295,0.00317,0.00885,0.01884,0.190,...,0.01373,0.03078,0.04398,21.209,0.462803,0.664357,-5.724056,0.190667,2.555477,0.148569

In [24]:
#Here its not in range. hence we need to perporm standardization

# Standadization
Standardization is a data preprocessing technique used in machine learning to trnasorm the data into a common scale in pandas. standardization can be achieved using the StandardScaler class from sklearn preprocessing module.

In [25]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [27]:
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [28]:
X_train

array([[-0.18147483, -0.3793974 ,  0.55407369, ..., -1.67395503,
        -0.14659208, -0.23012726],
       [ 1.40738776,  0.61453073, -0.89502937, ..., -0.44535179,
         0.4041514 , -0.6380504 ],
       [ 0.67973168, -0.05032717,  1.11000699, ..., -1.96582701,
        -0.10173777, -0.99131484],
       ...,
       [-0.85998512, -0.64307708, -0.14632838, ...,  1.20827479,
        -0.50997568, -0.21193639],
       [-0.32840677,  0.16786388, -0.77820183, ..., -0.21214574,
        -0.50861408,  0.28730688],
       [ 1.00497956,  0.16965798, -0.60620447, ..., -0.75765528,
         1.25703287, -0.05381239]])

# Training Model
we are using 6 model for training. and choose which one is best

In [30]:
from sklearn.svm import SVC

In [31]:
svc = SVC()
svc.fit(X_train,y_train)
y_pred = svc.predict(X_test)
y_pred

array([1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [32]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8974358974358975

## Lets try to check with other algorithms

In [33]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [36]:
models = {
    "lg":LogisticRegression(),
    "knc": KNeighborsClassifier(),
    "svc":SVC(),
    "gnb":GaussianNB(),
    "dtc":DecisionTreeClassifier(),
    "rfc":RandomForestClassifier(),
}
for name,model in models.items():
    model.fit(X_train,y_train)
    y_pred = model.predict(X_test)
    print(f"{name} with accucary:",accuracy_score(y_test,y_pred))

lg with accucary: 0.7692307692307693
knc with accucary: 0.9230769230769231
svc with accucary: 0.8974358974358975
gnb with accucary: 0.6923076923076923
dtc with accucary: 0.8461538461538461
rfc with accucary: 0.8461538461538461

C:\Users\CSC\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)

In [40]:
#WKT,KNeighborsClassifier has best accuracy compare to other, hence we gonna select this model: KNeighborsClassifier
model = KNeighborsClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
accuracy_score(y_test,y_pred)

C:\Users\CSC\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)

0.9230769230769231

# Prediction System

In [48]:
input_data = (-0.18147483, -0.3793974 ,  0.55407369, -0.34292574, -0.40526239,
       -0.28258268, -0.32355486, -0.28267185,  0.58058357,  0.45076651,
        0.74304418,  0.53593689,  0.30771145,  0.74337401, -0.14661736,
       -0.67628485, -0.42137602,  0.2729911 , -0.2504422 , -1.67395503,
       -0.14659208, -0.23012726)

np_data = np.asanyarray(input_data)
prediction = model.predict(np_data.reshape(1,-1))
if prediction[0] == 1:
    print("Has Parkinson Disease")
else:
    print("Has no Parkinson Disease")

Has Parkinson Disease

C:\Users\CSC\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)

In [38]:
X_train[0]

array([-0.18147483, -0.3793974 ,  0.55407369, -0.34292574, -0.40526239,
       -0.28258268, -0.32355486, -0.28267185,  0.58058357,  0.45076651,
        0.74304418,  0.53593689,  0.30771145,  0.74337401, -0.14661736,
       -0.67628485, -0.42137602,  0.2729911 , -0.2504422 , -1.67395503,
       -0.14659208, -0.23012726])

# Save Model

In [49]:
import pickle
pickle.dump(model,open("model.pkl",'wb'))