In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("Social_Network_Ads.csv")
df.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [3]:
#'Purchased' column is our output:

In [4]:
df.shape

(399, 5)

In [5]:
#To check the missing/null values
df.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [7]:
#To check the duplicated values
df.duplicated().sum()

0

In [8]:
#To check the basic statistic values
df.describe()

            User ID         Age  EstimatedSalary   Purchased
count  3.990000e+02  399.000000       399.000000  399.000000
mean   1.569138e+07   37.659148     69834.586466    0.358396
std    7.167752e+04   10.495709     34089.929941    0.480131
min    1.556669e+07   18.000000     15000.000000    0.000000
25%    1.562631e+07   29.500000     43000.000000    0.000000
50%    1.569429e+07   37.000000     70000.000000    0.000000
75%    1.575020e+07   46.000000     88000.000000    1.000000
max    1.581524e+07   60.000000    150000.000000    1.000000

In [14]:
#Encode the Gender
df['Gender'] = df['Gender'].map({'Male':1,'Female':0})

In [15]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(['User ID','Purchased'],axis=1),df['Purchased'],test_size = 0.2, random_state= 2)

In [16]:
X_train.shape

(319, 3)

In [17]:
X_test.shape

(80, 3)

In [19]:
#Scaling
from sklearn.preprocessing import StandardScaler

In [20]:
scaler = StandardScaler()

In [21]:
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [22]:
X_train

array([[-0.97217383,  1.95641335,  0.89423592],
       [-0.97217383, -1.69889532,  0.33714229],
       [-0.97217383, -1.02554898, -0.39587564],
       [ 1.02862263,  0.89829768, -1.39278002],
       [ 1.02862263, -1.79508765, -0.01470632],
       [-0.97217383,  0.03256668, -0.60112066],
       [-0.97217383,  0.32114368, -0.21995134],
       [ 1.02862263,  0.32114368, -0.3372342 ],
       [-0.97217383, -0.06362565, -0.24927205],
       [ 1.02862263,  2.14879802,  0.92355663],
       [-0.97217383,  1.18687468,  0.51306659],
       [ 1.02862263, -1.31412598, -1.51006289],
       [-0.97217383,  0.89829768, -0.68908281],
       [ 1.02862263,  0.41733602, -0.48383779],
       [-0.97217383,  0.89829768,  1.24608452],
       [-0.97217383, -1.12174132,  1.39268811],
       [ 1.02862263, -1.69889532,  0.45442516],
       [ 1.02862263, -0.54458732, -1.53938361],
       [ 1.02862263,  0.32114368, -0.74772424],
       [-0.97217383,  0.03256668, -0.60112066],
       [ 1.02862263,  1.86022102,  0.10257655],
       [ 1.02862263,  0.22495135, -0.1613099 ],
       [ 1.02862263, -0.64077965, -1.53938361],
       [-0.97217383,  0.03256668,  0.27850086],
       [-0.97217383,  1.76402868,  0.98219807],
       [ 1.02862263, -0.44839498, -1.15821429],
       [ 1.02862263, -0.73697198, -1.56870433],
       [-0.97217383, -1.41031832, -1.24617644],
       [ 1.02862263, -1.12174132,  0.45442516],
       [ 1.02862263, -0.25601032,  0.60102874],
       [ 1.02862263, -0.25601032, -0.95296926],
       [-0.97217383, -0.64077965, -1.07025213],
       [ 1.02862263,  0.03256668,  0.0146144 ],
       [ 1.02862263, -0.25601032, -1.27549715],
       [ 1.02862263,  1.09068235,  0.51306659],
       [-0.97217383, -0.06362565,  2.21366819],
       [-0.97217383, -0.92935665, -0.98228998],
       [ 1.02862263,  0.22495135,  0.21985942],
       [-0.97217383,  1.47545168, -1.07025213],
       [-0.97217383, -1.12174132,  0.27850086],
       [ 1.02862263,  0.03256668, -0.27859277],
       [-0.97217383,  1.37925935, -1.45142146],
       [ 1.02862263,  0.41733602, -0.19063062],
       [-0.97217383,  1.28306702,  1.86181958],
       [ 1.02862263,  0.89829768,  1.01151878],
       [ 1.02862263, -0.25601032, -0.60112066],
       [ 1.02862263, -1.12174132,  0.27850086],
       [-0.97217383,  0.70591302, -0.74772424],
       [ 1.02862263,  0.22495135,  0.13189727],
       [ 1.02862263,  0.03256668,  0.0146144 ],
       [-0.97217383,  0.12875902,  0.13189727],
       [ 1.02862263, -0.25601032,  0.07325584],
       [ 1.02862263,  0.22495135, -0.3372342 ],
       [ 1.02862263,  1.95641335,  2.15502675],
       [-0.97217383,  1.09068235, -0.92364855],
       [ 1.02862263,  0.80210535,  0.24918014],
       [ 1.02862263, -1.02554898, -1.48074217],
       [ 1.02862263, -0.25601032, -0.27859277],
       [-0.97217383, -0.25601032, -0.39587564],
       [-0.97217383, -1.12174132, -0.54247922],
       [-0.97217383,  0.41733602,  1.09948094],
       [ 1.02862263, -1.21793365,  0.57170803],
       [ 1.02862263, -1.12174132, -1.59802504],
       [ 1.02862263,  1.76402868,  1.83249887],
       [ 1.02862263,  0.41733602, -0.1613099 ],
       [ 1.02862263, -1.12174132, -1.12889357],
       [-0.97217383,  0.03256668, -0.1613099 ],
       [-0.97217383,  2.14879802,  1.09948094],
       [-0.97217383, -0.15981798,  1.62725385],
       [ 1.02862263,  0.41733602,  0.98219807],
       [ 1.02862263, -0.54458732, -1.53938361],
       [-0.97217383, -1.12174132, -1.04093142],
       [-0.97217383, -0.73697198,  1.33404667],
       [ 1.02862263,  0.12875902,  1.86181958],
       [ 1.02862263,  0.32114368, -0.54247922],
       [-0.97217383,  0.70591302, -1.42210074],
       [ 1.02862263,  0.03256668, -0.3372342 ],
       [ 1.02862263, -0.25601032, -1.48074217],
       [-0.97217383, -0.83316432, -0.68908281],
       [-0.97217383, -1.02554898, -1.15821429],
       [-0.97217383, -0.06362565,  0.0146144 ],
       [ 1.02862263,  0.99449002,  0.10257655],
       [ 1.02862263,  0.99449002, -1.09957285],
       [-0.97217383, -1.02554898, -0.36655492],
       [ 1.02862263, -1.79508765,  0.16121799],
       [-0.97217383, -1.79508765, -1.45142146],
       [-0.97217383,  1.95641335,  0.71831161],
       [ 1.02862263,  0.22495135, -0.39587564],
       [ 1.02862263, -1.60270298,  0.04393512],
       [-0.97217383, -0.64077965,  1.39268811],
       [-0.97217383, -0.06362565,  0.27850086],
       [ 1.02862263, -0.35220265,  1.30472596],
       [-0.97217383,  0.32114368,  0.04393512],
       [ 1.02862263, -0.64077965,  0.16121799],
       [-0.97217383, -1.50651065, -0.45451707],
       [-0.97217383, -1.02554898,  0.39578372],
       [-0.97217383,  1.57164402,  1.09948094],
       [ 1.02862263,  0.70591302, -1.12889357],
       [ 1.02862263,  0.80210535, -0.3372342 ],
       [ 1.02862263,  1.09068235, -0.1613099 ],
       [ 1.02862263, -1.69889532, -0.63044138],
       [-0.97217383,  1.47545168,  0.98219807],
       [-0.97217383, -1.31412598, -1.27549715],
       [-0.97217383,  0.22495135,  0.04393512],
       [ 1.02862263,  2.14879802,  0.36646301],
       [-0.97217383, -0.92935665,  0.42510444],
       [-0.97217383,  2.05260568,  0.36646301],
       [ 1.02862263, -1.89127998,  0.33714229],
       [-0.97217383,  0.80210535, -1.42210074],
       [ 1.02862263,  0.89829768, -0.80636568],
       [ 1.02862263,  0.80210535, -1.24617644],
       [-0.97217383,  0.22495135, -0.30791349],
       [-0.97217383, -0.25601032,  2.24298891],
       [-0.97217383,  1.37925935,  1.97910245],
       [-0.97217383, -0.15981798, -0.60112066],
       [-0.97217383,  0.89829768,  2.15502675],
       [-0.97217383, -0.44839498,  2.30163034],
       [-0.97217383,  0.51352835,  1.83249887],
       [ 1.02862263,  0.22495135, -0.68908281],
       [ 1.02862263,  1.66783635, -0.92364855],
       [-0.97217383, -0.15981798,  0.13189727],
       [ 1.02862263,  0.22495135,  0.0146144 ],
       [-0.97217383,  0.70591302,  1.77385743],
       [-0.97217383, -0.35220265, -1.33413859],
       [ 1.02862263,  0.12875902,  0.0146144 ],
       [-0.97217383, -0.92935665,  0.39578372],
       [ 1.02862263, -0.06362565, -0.45451707],
       [-0.97217383, -0.92935665, -0.45451707],
       [ 1.02862263, -1.79508765,  0.42510444],
       [-0.97217383, -0.83316432, -1.24617644],
       [ 1.02862263, -0.92935665, -0.3372342 ],
       [-0.97217383,  0.99449002,  0.74763233],
       [-0.97217383, -1.60270298, -0.07334775],
       [ 1.02862263, -1.02554898, -0.36655492],
       [ 1.02862263,  1.09068235,  0.54238731],
       [ 1.02862263, -0.64077965, -0.36655492],
       [-0.97217383, -1.12174132, -1.56870433],
       [ 1.02862263,  0.32114368,  0.48374588],
       [-0.97217383, -0.64077965, -1.62734576],
       [ 1.02862263,  0.22495135, -0.39587564],
       [ 1.02862263, -0.06362565,  0.10257655],
       [-0.97217383,  1.37925935, -0.95296926],
       [ 1.02862263, -0.15981798, -0.54247922],
       [-0.97217383,  1.66783635,  1.74453671],
       [-0.97217383,  0.60972068,  2.00842317],
       [ 1.02862263,  0.03256668, -0.27859277],
       [-0.97217383, -0.44839498, -0.30791349],
       [-0.97217383,  0.32114368,  0.04393512],
       [-0.97217383,  0.41733602, -0.51315851],
       [-0.97217383, -1.02554898, -1.56870433],
       [-0.97217383,  0.89829768,  1.07016022],
       [ 1.02862263, -1.50651065,  0.30782157],
       [ 1.02862263, -0.25601032,  0.13189727],
       [ 1.02862263,  0.12875902, -0.8356864 ],
       [ 1.02862263,  0.22495135,  1.07016022],
       [-0.97217383,  1.95641335, -1.39278002],
       [-0.97217383, -0.44839498, -0.04402703],
       [-0.97217383,  0.41733602, -0.01470632],
       [-0.97217383, -0.25601032, -0.1613099 ],
       [ 1.02862263, -0.73697198, -0.63044138],
       [ 1.02862263,  1.28306702, -1.39278002],
       [ 1.02862263, -1.41031832, -1.48074217],
       [-0.97217383, -0.15981798, -0.48383779],
       [-0.97217383,  1.86022102, -1.30481787],
       [ 1.02862263, -0.15981798,  1.39268811],
       [-0.97217383,  0.80210535, -0.86500711],
       [-0.97217383, -0.44839498, -1.24617644],
       [ 1.02862263, -0.73697198,  1.8911403 ],
       [ 1.02862263, -0.25601032,  1.09948094],
       [ 1.02862263, -0.25601032, -0.45451707],
       [ 1.02862263,  0.41733602, -0.1613099 ],
       [-0.97217383, -0.54458732,  1.8911403 ],
       [ 1.02862263, -0.92935665,  0.24918014],
       [-0.97217383, -1.89127998,  0.45442516],
       [-0.97217383, -1.31412598,  0.54238731],
       [-0.97217383,  0.22495135,  0.13189727],
       [ 1.02862263, -0.06362565, -0.01470632],
       [ 1.02862263,  0.99449002,  2.0670646 ],
       [-0.97217383, -0.06362565,  0.21985942],
       [-0.97217383, -1.69889532, -1.0116107 ],
       [ 1.02862263,  0.22495135, -0.39587564],
       [ 1.02862263, -1.79508765, -1.33413859],
       [-0.97217383,  1.95641335, -0.68908281],
       [-0.97217383,  0.41733602,  0.13189727],
       [ 1.02862263, -1.02554898,  0.54238731],
       [ 1.02862263, -1.21793365, -1.09957285],
       [-0.97217383, -0.06362565, -0.39587564],
       [-0.97217383, -0.06362565,  0.27850086],
       [-0.97217383,  0.89829768, -0.60112066],
       [-0.97217383, -1.79508765, -1.30481787],
       [-0.97217383,  0.03256668,  1.2167638 ],
       [-0.97217383,  0.89829768, -0.63044138],
       [-0.97217383,  2.14879802, -0.71840353],
       [ 1.02862263,  2.14879802, -0.8356864 ],
       [-0.97217383,  0.99449002, -1.04093142],
       [-0.97217383,  1.86022102, -1.09957285],
       [-0.97217383, -0.92935665,  0.48374588],
       [ 1.02862263, -1.21793365,  0.24918014],
       [-0.97217383,  0.80210535, -1.12889357],
       [-0.97217383,  0.12875902,  0.24918014],
       [-0.97217383,  0.32114368,  0.04393512],
       [ 1.02862263,  2.05260568,  2.12570604],
       [-0.97217383,  0.41733602,  0.57170803],
       [-0.97217383, -0.25601032,  0.77695305],
       [ 1.02862263, -1.41031832, -0.21995134],
       [ 1.02862263,  1.09068235,  0.10257655],
       [ 1.02862263,  1.57164402, -0.01470632],
       [-0.97217383,  0.12875902,  0.0146144 ],
       [ 1.02862263,  0.89829768, -1.07025213],
       [ 1.02862263, -0.54458732,  1.45132954],
       [ 1.02862263, -1.12174132, -1.62734576],
       [-0.97217383,  1.28306702,  2.21366819],
       [-0.97217383, -1.41031832, -0.13198918],
       [ 1.02862263, -1.79508765, -1.51006289],
       [-0.97217383,  0.89829768, -1.187535  ],
       [-0.97217383,  1.57164402, -1.30481787],
       [-0.97217383,  0.60972068, -0.92364855],
       [ 1.02862263, -1.21793365, -1.42210074],
       [-0.97217383, -0.44839498, -0.86500711],
       [ 1.02862263, -0.83316432, -0.27859277],
       [-0.97217383,  1.47545168,  2.12570604],
       [-0.97217383,  0.03256668,  1.24608452],
       [ 1.02862263, -0.25601032,  0.24918014],
       [ 1.02862263, -1.12174132, -1.187535  ],
       [ 1.02862263, -0.73697198,  0.54238731],
       [ 1.02862263,  0.12875902,  1.0408395 ],
       [-0.97217383, -0.54458732,  1.36336739],
       [-0.97217383,  0.12875902,  1.86181958],
       [-0.97217383,  0.22495135,  2.09638532],
       [ 1.02862263,  0.12875902,  1.50997098],
       [ 1.02862263, -1.69889532,  0.10257655],
       [ 1.02862263, -0.25601032, -0.51315851],
       [ 1.02862263,  0.12875902,  0.74763233],
       [ 1.02862263,  0.89829768, -1.33413859],
       [-0.97217383, -0.25601032, -0.30791349],
       [ 1.02862263, -0.15981798,  0.83559448],
       [-0.97217383,  0.41733602,  0.27850086],
       [ 1.02862263, -0.15981798,  1.59793313],
       [-0.97217383,  0.12875902, -0.3372342 ],
       [ 1.02862263, -0.92935665,  1.53929169],
       [-0.97217383,  0.12875902, -0.27859277],
       [ 1.02862263, -1.21793365,  0.48374588],
       [ 1.02862263,  0.12875902, -0.8356864 ],
       [-0.97217383,  1.09068235, -1.0116107 ],
       [-0.97217383,  0.99449002,  1.77385743],
       [-0.97217383, -1.41031832, -0.65976209],
       [-0.97217383,  0.99449002, -1.21685572],
       [ 1.02862263, -1.31412598, -0.45451707],
       [ 1.02862263,  0.32114368,  0.04393512],
       [-0.97217383, -0.25601032, -0.60112066],
       [ 1.02862263, -0.73697198,  1.07016022],
       [-0.97217383,  1.57164402,  0.98219807],
       [ 1.02862263, -1.02554898,  0.57170803],
       [ 1.02862263,  0.41733602,  0.07325584],
       [-0.97217383, -0.92935665, -0.3372342 ],
       [-0.97217383,  1.18687468, -0.77704496],
       [ 1.02862263, -1.89127998, -0.54247922],
       [ 1.02862263,  1.09068235, -1.24617644],
       [ 1.02862263,  0.32114368,  0.24918014],
       [ 1.02862263, -0.73697198, -1.62734576],
       [-0.97217383, -0.25601032, -1.33413859],
       [ 1.02862263, -0.25601032,  0.51306659],
       [-0.97217383,  0.99449002,  1.86181958],
       [ 1.02862263, -0.64077965, -0.13198918],
       [-0.97217383, -0.44839498,  1.24608452],
       [ 1.02862263,  0.32114368, -0.54247922],
       [-0.97217383,  1.86022102,  1.50997098],
       [ 1.02862263,  1.09068235,  0.45442516],
       [-0.97217383,  2.05260568,  0.16121799],
       [-0.97217383, -1.69889532,  0.33714229],
       [-0.97217383, -0.15981798, -0.21995134],
       [-0.97217383, -0.64077965,  0.54238731],
       [-0.97217383,  1.37925935,  1.27540524],
       [ 1.02862263,  1.76402868, -0.30791349],
       [ 1.02862263,  1.09068235, -1.24617644],
       [ 1.02862263, -0.73697198,  0.48374588],
       [-0.97217383, -1.31412598, -1.12889357],
       [-0.97217383,  0.80210535,  0.33714229],
       [-0.97217383, -0.83316432,  0.36646301],
       [ 1.02862263, -0.73697198,  0.27850086],
       [-0.97217383, -1.02554898,  1.94978173],
       [ 1.02862263, -0.06362565,  0.04393512],
       [ 1.02862263,  1.37925935,  2.33095106],
       [ 1.02862263, -0.06362565,  0.13189727],
       [-0.97217383, -0.06362565,  1.94978173],
       [-0.97217383, -0.73697198,  0.24918014],
       [ 1.02862263, -1.12174132,  0.30782157],
       [-0.97217383,  0.32114368, -0.30791349],
       [-0.97217383,  0.99449002, -1.187535  ],
       [-0.97217383,  1.37925935,  0.57170803],
       [ 1.02862263, -1.50651065, -1.53938361],
       [-0.97217383, -0.92935665, -0.77704496],
       [-0.97217383, -1.12174132,  0.04393512],
       [ 1.02862263,  0.41733602, -0.48383779],
       [-0.97217383, -1.89127998, -0.77704496],
       [-0.97217383,  0.41733602,  0.24918014],
       [-0.97217383, -0.25601032,  0.1905387 ],
       [-0.97217383, -0.54458732,  0.45442516],
       [ 1.02862263, -0.35220265, -0.80636568],
       [-0.97217383, -0.25601032,  0.0146144 ],
       [ 1.02862263, -0.06362565,  0.1905387 ],
       [ 1.02862263, -0.25601032,  0.13189727],
       [-0.97217383,  0.32114368, -0.57179994],
       [-0.97217383,  0.80210535,  0.74763233],
       [-0.97217383,  0.99449002,  1.97910245],
       [ 1.02862263, -0.15981798, -0.30791349],
       [-0.97217383, -1.02554898, -0.48383779],
       [ 1.02862263, -0.25601032, -0.36655492],
       [ 1.02862263,  2.14879802, -0.8356864 ],
       [-0.97217383, -0.25601032, -0.77704496],
       [-0.97217383, -0.06362565, -1.09957285],
       [-0.97217383, -0.25601032,  0.04393512],
       [ 1.02862263,  0.51352835,  1.715216  ],
       [ 1.02862263, -0.35220265,  1.2167638 ],
       [ 1.02862263,  0.80210535,  1.36336739],
       [ 1.02862263,  0.99449002, -0.86500711],
       [-0.97217383, -1.69889532, -1.39278002],
       [ 1.02862263, -0.83316432,  0.27850086],
       [ 1.02862263, -0.83316432,  2.27230962]])

# Training Models

In [23]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

In [25]:
models = {
    'lg':LogisticRegression(),
    'dtc':DecisionTreeClassifier(),
    'rfc':RandomForestClassifier(),
    'gnb':GaussianNB()
}
for name,model in models.items():
    model.fit(X_train,y_train)
    y_pred = model.predict(X_test)
    print(f"{name} with accuracy: {accuracy_score(y_test,y_pred)}")

lg with accuracy: 0.8125
dtc with accuracy: 0.8625
rfc with accuracy: 0.9125
gnb with accuracy: 0.8625

In [26]:
#We selected Random Forest Classifier model
rfc = RandomForestClassifier()
rfc.fit(X_train,y_train)
y_pred = rfc.predict(X_test)
accuracy_score(y_test,y_pred)

0.9125

# Prediction System

In [29]:
input_text = (-0.97217383,  1.95641335,  0.89423592)
input_np_text = np.asarray(input_text)
prediction = rfc.predict(input_np_text.reshape(1,-1))
if prediction == 1:
    print("purchased")
else:
    print("Not Purchased")

purchased

In [30]:
X_train[0]

array([-0.97217383,  1.95641335,  0.89423592])

# Save Model

In [31]:
import pickle
pickle.dump(rfc,open('model.pkl','wb'))