In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv("Titanic Servivors Dataset.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [3]:
# 'Survived' column is our output
df['Survived'].value_counts()

0    265
1    151
Name: Survived, dtype: int64

In [8]:
#shape
df.shape

(416, 12)

In [13]:
#to check datatype
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 416 entries, 0 to 415
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  416 non-null    int64
 1   Survived     416 non-null    int64
 2   Pclass       416 non-null    int64
 3   Name         416 non-null    object
 4   Sex          416 non-null    object
 5   Age          331 non-null    float64
 6   SibSp        416 non-null    int64
 7   Parch        416 non-null    int64
 8   Ticket       416 non-null    object
 9   Fare         415 non-null    float64
 10  Cabin        91 non-null     object
 11  Embarked     416 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 39.1+ KB

In [12]:
#To check null/missing values
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             85
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          325
Embarked         0
dtype: int64

In [14]:
#any how I don't need Cabin column hence drop
df.drop('Cabin',axis=1,inplace=True)

In [15]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,S

In [19]:
#Convert categorical column into numeric column
df['Sex'].value_counts()

male      265
female    151
Name: Sex, dtype: int64

In [20]:
df['Embarked'].value_counts()

S    268
C    102
Q     46
Name: Embarked, dtype: int64

In [49]:
df.replace({'Sex':{'male':0,'female':1},'Embarked':{'S':0,'C':1,'Q':2}},inplace=True)

In [50]:
df['Age'].isnull().sum()

0

In [51]:
#In Age we have null values, we need to drop it
df.dropna(inplace=True)
df['Age'].isnull().sum()

0

In [52]:
df['Sex'].value_counts()

0    204
1    126
Name: Sex, dtype: int64

In [53]:
#Split into x and y axis
X= df.drop(['Survived','PassengerId','Name','Ticket'], axis=1)
y = df['Survived']

In [54]:
X.shape

(330, 7)

In [55]:
y.shape

(330,)

### Train test split

In [56]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)

In [57]:
X_train.shape

(264, 7)

## Traning Model

In [58]:
lg = LogisticRegression()
lg.fit(X_train,y_train)
y_pred = lg.predict(X_test)
y_pred

C:\Users\CSC\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

array([0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1],
      dtype=int64)

In [59]:
#Accuracy Score
accuracy_score(y_test,y_pred)

1.0

In [60]:
#Accuracy = 100%

# Prediction

In [63]:
input_data = (3,0,34.5,0,0,7.8292,2)
np_array = np.asarray(input_data)
pred = lg.predict(np_array.reshape(1,-1))
if pred[0] == 0:
    print("The person Survived")
else:
    print("The Person Dead!!")

The person Survived

C:\Users\CSC\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(